from pydantic import BaseModel, Field

class QueryRequest(BaseModel):
    query: str = Field(..., description = "Query from recruiter")

class QueryResponse(BaseModel):
    answer: str = Field(..., description = "Answer generated by the LangGraph agent.")

class UploadResponse(BaseModel):
    message: str = Field(..., description = "Message about status  of chunking and embedding process.")

class ChatRequest(BaseModel):
    message: str
    model_config = {
        "json_schema_extra":{
            "example": {
                "message": "Hello, I am looking for a software engineer with experience in Python and machine learning."
                
            }
        }
    }