from pydantic import BaseModel, Field

class QueryRequest(BaseModel):
    query: str = Field(..., description = "Query from recruiter")

class QueryResponse(BaseModel):
    answer: str = Field(..., description = "Answer generated by the LangGraph agent.")

class UploadResponse(BaseModel):
    message: str = Field(..., description = "Message about status  of chunking and embedding process.")